#Este archivo va a declar como se va a iniciar
#Y desde donde se va a iniciar el contenedor
services:
#Cambiar nombre de app
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
#Lo que le vamos a decir es:
#Vas a construir este servicio desde el contexto (.)
#o carpeta en la que estoy ubicado y buscaras el 
#archivo Dockerfile para construir el contenedor
    volumes:
      - .:/app
#Evidenciar o enlazar puertos
    ports:
    - '80:80'